export enum AttendanceStatuses {
  ENTRY = 'ENTRADA NORMAL',
  DELAYED_ENTRY = 'ENTRADA CON RETARDO',
  EARLY_EXIT_ATTENDANCE = 'ASISTENCIA CON SALIDA ANTICIPADA',
  NORMAL_ATTENDANCE = 'ASISTENCIA NORMAL',
  ABSENCE = 'FALTA',
}
